const express = require('express');
const app = express();
const server = require('http').Server(app)
const io = require('socket.io')(server)
app.set('view engine', 'ejs');

// importing version 4 uuid
// uuid basically provides a unique id to the rooms
const {v4:uuidv4} = require('uuid');
app.use(express.static('public'));

const PORT = 8000;

//Actually what's going on here is we're redirecting to unique id generated by this function uuidv4() will create a unique id   
app.get('/', (req, res) => {
    res.redirect(`/${uuidv4()}`);
});

app.get('/:room', (req, res)=>{
    res.render('room', {roomId: req.params.room});
});




io.on('connection', socket => {
    Socket.on('join-room', () =>{
        console.log("joined room");
    })
})




server.listen(PORT,(err) =>{
    if(err){
        console.log('Error in setting up a server');
    }
    console.log('Successfully set up the express server', PORT);
})

